### ISSUE TITLE
Don't use .NET Framework

### ISSUE THREAD

**Issue by RheaAyase** [justcool393/BotTerminator#5]
.NET Framework is obsolete and will soon be deprecated, replaced by .NET Core aka .NET 5 in less than one year. I strongly recommend you to use .NET Core right away. Which would also allow this to be deployed in production (on a proper server) and not just on a windows laptop, since .NET Framework can not run on any non-x64 architecture and non-windows platform. .NET Core was designed for back end services while Framework is a desktop application platform.

Use the .NET Core SDK version 3.0101 (target runtime 3.0.0) and when 3.1 is announced (on roadmap by the end of the year) switch to that, as 3.1 is LTS and 3.0 is not.

Further I recommend creating an empty console app using cli `dotnet new console` instead of creating it using VS because it adds a lot of unnecessary bloat to the project. Then just copypaste the code files into src subdirectory.

**Comment by justcool393** [comment]
Implemented in #8. Thanks for the PR 👍
