### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by RheaAyase** [justcool393/BotTerminator#6]
Please follow standardized naming conventions. Don't use lowercase single letter member variable names, and don't even use single letter local variables. Properties have to be PascalCase, locals would be cammelCase, and when addressing member variables, you can also use `this.` The code is full of random abbreviations. Writing clean and readable code improves the ease to contribute to open source projects.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines

**Comment by justcool393** [comment]
completed
